### ISSUE TITLE
An error was encountered while the XamlFileGenerator was parsing IList<T> property

### ISSUE THREAD

**Issue by Daoting** [nventive/Uno#189]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one)  
 

## Current behavior

xaml like this:
`<dt:SingleWin.Bar>
        <dt:Btn />
        <dt:Btn />
        <dt:Btn />
    </dt:SingleWin.Bar>`

The Bar's define:
`public IList<IBarElement> Bar
        {
            get { return _bar.Commands; }
        }`

XamlFileGenerator code:
// WARNING Property c8.base does not exist on {using:Dt.Base}SingleWin, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
				c8.Bar = 
				{
					new global::Dt.Base.Btn
					{
						// Source ..\..\..\..\..\..\Win\SingleWinDemo.xaml (Line 8:10)
					}
					,
				}
## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

```

**Comment by jeromelaban** [comment]
Thanks for the report! This was recently fixed by @dr1rrb in https://github.com/nventive/Uno/pull/184.

Your sample now does this:

```
<local:SingleWin>
	<local:SingleWin.Bar>
		<local:Btn />
		<local:Btn />
		<local:Btn />
	</local:SingleWin.Bar>
</local:SingleWin>

```

```
new global::App69.SingleWin
{
	Bar = 
	{
		new global::App69.Btn
		{
			// Source ..\..\..\..\..\..\..\App69.Shared\MainPage.xaml (Line 15:6)
		}
		,
		new global::App69.Btn
		{
			// Source ..\..\..\..\..\..\..\App69.Shared\MainPage.xaml (Line 16:6)
		}
		,
		new global::App69.Btn
		{
			// Source ..\..\..\..\..\..\..\App69.Shared\MainPage.xaml (Line 17:6)
		}
		,
	}
	,
	// Source ..\..\..\..\..\..\..\App69.Shared\MainPage.xaml (Line 13:4)
}
```

**Comment by Daoting** [comment]
Great! 👍

**Comment by Daoting** [comment]
@jeromelaban
 It still exists error. It looks like the Apply method is not generated because of the Bar type not found. XamlFileGenerator code:
`this
.Apply((c9 => 
{
	// Source Frame\PageWinDemo.xaml (Line 1:2)
	
	// WARNING Property c9.base does not exist on {using:Dt.Base}PageWin, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
	c9.Bar = 
	{
		new global::Dt.Base.Btn
		{
			// Source ..\..\..\..\..\..\Frame\PageWinDemo.xaml (Line 8:10)
		}
		,
		new global::Dt.Base.Btn
		{
			// Source ..\..\..\..\..\..\Frame\PageWinDemo.xaml (Line 9:10)
		}
		,
		new global::Dt.Base.ToggleBtn
		{
			// Source ..\..\..\..\..\..\Frame\PageWinDemo.xaml (Line 20:10)
		}
		,
	}
	;
}`

**Comment by Daoting** [comment]
SingleWin is root element 
```
<local:SingleWin>
	<local:SingleWin.Bar>
		<local:Btn />
		<local:Btn />
		<local:Btn />
	</local:SingleWin.Bar>
</local:SingleWin>
```
The Bar's define:
`public IList<IBarElement> Bar { get { return _bar.Commands; } }`
